import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export function parseVersion(value) {
  const match = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$/.exec(value);
  if (!match) throw new Error('Invalid SemVer');
  return { version: value, prerelease: match[4] ?? '' };
}
export function versionFiles(version, base = root) {
  if (parseVersion(version).prerelease) throw new Error('Only stable version synchronization is enabled; beta Worker version mapping is not yet implemented');
  const result = new Map();
  const read = (path) => readFileSync(resolve(base, path), 'utf8');
  for (const path of ['package.json', 'apps/desktop/package.json', 'packages/shared-types/package.json', 'apps/desktop/src-tauri/tauri.conf.json']) {
    const data = JSON.parse(read(path)); data.version = version;
    result.set(path, JSON.stringify(data, null, 2) + '\n');
  }
  for (const path of ['apps/desktop/src-tauri/Cargo.toml', 'services/ai-worker/pyproject.toml']) {
    result.set(path, read(path).replace(/^version = "[^"]+"/m, `version = "${version}"`));
  }
  for (const [path, name] of [['apps/desktop/src-tauri/Cargo.lock', 'shiwei-desktop'], ['services/ai-worker/uv.lock', 'shiwei-ai']]) {
    result.set(path, read(path).replace(new RegExp(`(name = "${name}"\\r?\\nversion = ")[^"]+"`), `$1${version}"`));
  }
  result.set('services/ai-worker/shiwei_ai/__init__.py', read('services/ai-worker/shiwei_ai/__init__.py').replace(/__version__ = "[^"]+"/, `__version__ = "${version}"`));
  result.set('apps/desktop/src/release-version.ts', `// Generated by scripts/version.mjs; VERSION is the release source of truth.\nexport const APP_VERSION = "${version}";\n`);
  result.set('VERSION', version + '\n');
  return result;
}
export function validateVersion(base = root, tag) {
  const version = readFileSync(resolve(base, 'VERSION'), 'utf8').trim();
  if (tag && tag !== `v${version}`) throw new Error('Tag does not match VERSION');
  for (const [path, expected] of versionFiles(version, base)) {
    if (readFileSync(resolve(base, path), 'utf8').replace(/\r\n/g, '\n') !== expected.replace(/\r\n/g, '\n')) throw new Error(`Version drift: ${path}`);
  }
  return version;
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const argument = process.argv[2];
  if (argument === '--check') console.log(`Release version validated: ${validateVersion(root, process.argv[3])}`);
  else {
    const version = parseVersion(argument ?? readFileSync(resolve(root, 'VERSION'), 'utf8').trim()).version;
    for (const [path, content] of versionFiles(version)) writeFileSync(resolve(root, path), content);
    console.log(`Release version synchronized: ${version}`);
  }
}
